[package]
name = "juggernaut"
version = "0.1.0"
authors = ["Afshin Mehrabani <afshin.meh@gmail.com>"]
description = "Neural Network in Rust"
license = "GPL-3.0"

[dependencies]
assert_approx_eq = "1.0.0"
rand = "*"
